DROP TABLE PF;
DROP TABLE PJ;
DROP TABLE FONE_CLIENTE;
DROP TABLE FONE_VENDEDOR;
DROP TABLE PRATELEIRA;
DROP TABLE PRODUTO;
DROP TABLE CLIENTE;
DROP TABLE VENDEDOR;

CREATE TABLE CLIENTE
(
CODIGO  NUMBER CONSTRAINT PK_CLIENTE PRIMARY KEY,
NOME    VARCHAR2(60) NOT NULL,
RUA     VARCHAR2(80) NOT NULL,
NR      NUMBER(4) NOT NULL,
BAIRRO  VARCHAR2(50) NOT NULL,
COMPLEMENTO VARCHAR2(100),
CIDADE  VARCHAR2(50) NOT NULL,
UF      VARCHAR2(2) NOT NULL,
CEP     VARCHAR2(10) NOT NULL
);

CREATE TABLE PF
(
CODIGO_CLI      NUMBER CONSTRAINT PK_PF PRIMARY KEY,
CNPF            VARCHAR2(14) NOT NULL,
RG              VARCHAR2(10) NOT NULL,
DATA_NASCIMENTO DATE NOT NULL
);

ALTER TABLE PF
ADD CONSTRAINT FK_PF_CLIENTE FOREIGN KEY (CODIGO_CLI) REFERENCES CLIENTE (CODIGO);

CREATE TABLE PJ
(
CODIGO_CLI      NUMBER CONSTRAINT PK_PJ PRIMARY KEY,
CNPJ            VARCHAR2(19) NOT NULL,
IE              VARCHAR2(10) NOT NULL,
NOME_FANTASIA   VARCHAR2(60) NOT NULL
);

ALTER TABLE PJ
ADD CONSTRAINT FK_PJ_CLIENTE FOREIGN KEY (CODIGO_CLI) REFERENCES CLIENTE (CODIGO);

CREATE TABLE FONE_CLIENTE
(
NUMERO        VARCHAR2(14),
CODIGO_CLI    NUMBER,
CONSTRAINT PF_FONE_CLIENTE PRIMARY KEY (NUMERO, CODIGO_CLI)
);

ALTER TABLE FONE_CLIENTE
ADD CONSTRAINT FK_FONE_CLIENTE FOREIGN KEY (CODIGO_CLI) REFERENCES CLIENTE (CODIGO);

CREATE TABLE VENDEDOR
(
MATRICULA   NUMBER CONSTRAINT PK_VENDEDOR PRIMARY KEY,
NOME        VARCHAR2(60) NOT NULL,
CNPF        VARCHAR2(14) NOT NULL
);

CREATE TABLE FONE_VENDEDOR
(
NUMERO          VARCHAR2(14),
MATRICULA_VEN   NUMBER,
CONSTRAINT PK_FONE_VENDEDOR PRIMARY KEY (NUMERO, MATRICULA_VEN)
);

ALTER TABLE FONE_VENDEDOR
ADD CONSTRAINT FK_FONE_VENDEDOR FOREIGN KEY (MATRICULA_VEN) REFERENCES VENDEDOR (MATRICULA);

CREATE TABLE PRODUTO
(
CODIGO      NUMBER CONSTRAINT PK_PRODUTO PRIMARY KEY,
DESCRICAO   VARCHAR2(80) NOT NULL,
UNID_MEDIDA VARCHAR2(10) NOT NULL
);

CREATE TABLE PRATELEIRA
(
CODIGO          NUMBER(3) CONSTRAINT PK_PRATELEIRA PRIMARY KEY,
DESCRICAO       VARCHAR2(50) NOT NULL,
NUMERO_SECOES   NUMBER(2) NOT NULL
);

CREATE TABLE PEDIDO
(
NUMERO            NUMBER(6) CONSTRAINT PK_PEDIDO PRIMARY KEY,
DATA              DATE NOT NULL,
PRAZO_ENTREGA     DATE,
RUA               VARCHAR2(80),
NR                NUMBER(4),
BAIRRO            VARCHAR2(50),
COMPLEMENTO       VARCHAR2(100),
CIDADE            VARCHAR2(50),
UF                VARCHAR2(2),  
CEP               VARCHAR2(10),
TOTAL_FATURA      NUMBER(8,2),
CODIGO_CLI        NUMBER NOT NULL,
MATRICULA_VEN     NUMBER NOT NULL
);

ALTER TABLE PEDIDO
ADD CONSTRAINT FK_PED_CLIENTE FOREIGN KEY (CODIGO_CLI) REFERENCES CLIENTE (CODIGO);

ALTER TABLE PEDIDO
ADD CONSTRAINT FK_PED_VENDEDOR FOREIGN KEY (MATRICULA_VEN) REFERENCES VENDEDOR (MATRICULA);

CREATE TABLE ITEM_PRODUTO
(
CODIGO_PRO        NUMBER,
NUMERO_PED        NUMBER(6),
QUANTIDADE        NUMBER(5),
PRECO_UNITARIO    NUMBER(5,2),
VALOR_ITEM        NUMBER(7,2),
CONSTRAINT PK_ITEM_PRODUTO PRIMARY KEY (CODIGO_PRO, NUMERO_PED)
);

ALTER TABLE ITEM_PRODUTO
ADD CONSTRAINT FK_ITEM_PEDIDO FOREIGN KEY (NUMERO_PED) REFERENCES PEDIDO (NUMERO);

ALTER TABLE ITEM_PRODUTO
ADD CONSTRAINT FK_ITEM_PRODUTO FOREIGN KEY (CODIGO_PRO) REFERENCES PRODUTO (CODIGO);










